### ISSUE TITLE
MVPリリースレビュー依頼

### ISSUE THREAD

**Issue by jyasco** [jyasco/purin-mania#197]
MVPリリースのレビューを提出させていただきます。
お忙しいところ恐れ入りますが、ご確認のほどどうぞよろしくお願いいたします。

---

## 各種情報
**サービスの概要とMVPで検証する事柄：**
「Purin Mania」は、プリン愛好家のためのレビュー・検索アプリです。
ユーザーはプリンの固さや甘さなどを詳細に評価し、共有できます。
また、固さや甘さでの絞り込みや並び替え検索によってユーザーは自分好みのプリンを簡単に見つけることができます。

**サービス名：** PurinMania（プリンマニア）
**サービスURL：** https://purin-mania.onrender.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] アカウント登録
- [x] ログイン/ログアウト機能
- [ ] パスワードリセット機能
- [x] 投稿作成機能
- [x] 投稿一覧機能
- [x] 投稿編集機能
- [x] 投稿削除機能
- [x] 検索機能
- [x] Xシェア機能

## READMEレビュー時から変更した機能

**以下を追加で実装しました。**
- [x] ブックマーク機能
- [x] 動的OGPの実装
- [x] マイページ機能

**以下は本リリースにて実装いたします**
- [ ] パスワードリセット機能

## サービスイメージがわかるようなスクリーンショット等
|トップ画面 |プリン一覧・検索機能|
|:--:|:--:|
|[![Image from Gyazo](https://i.gyazo.com/7e32c08f8f042e70b9532b9d0ef3274c.png)](https://gyazo.com/7e32c08f8f042e70b9532b9d0ef3274c)|[![Image from Gyazo](https://i.gyazo.com/c1135814118e7da686c07e1cf01c8ada.png)](https://gyazo.com/c1135814118e7da686c07e1cf01c8ada)|

|新規登録画面|ログイン画面|
|:--:|:--:|
|[![Image from Gyazo](https://i.gyazo.com/1723fabbe864772afe9dd74bc8f63607.png)](https://gyazo.com/1723fabbe864772afe9dd74bc8f63607)|[![Image from Gyazo](https://i.gyazo.com/ff8cbd108d4dc30eb024e29f6a0fe901.png)](https://gyazo.com/ff8cbd108d4dc30eb024e29f6a0fe901)|

|投稿作成|投稿詳細|
|:--:|:--:|
|[![Image from Gyazo](https://i.gyazo.com/6e23057c5fa34bb52a31aee0f783eac3.png)](https://gyazo.com/6e23057c5fa34bb52a31aee0f783eac3)|[![Image from Gyazo](https://i.gyazo.com/8d1b961e1ad63817275abb5a2c767946.png)](https://gyazo.com/8d1b961e1ad63817275abb5a2c767946)|

|マイページ|プロフィール編集|
|:--:|:--:|
|[![Image from Gyazo](https://i.gyazo.com/7b066c6a3d1a25fa86ffd23a15412277.png)](https://gyazo.com/7b066c6a3d1a25fa86ffd23a15412277)|[![Image from Gyazo](https://i.gyazo.com/75157d95416982a99ae2d06d30b81f48.png)](https://gyazo.com/75157d95416982a99ae2d06d30b81f48)|

**Comment by kenchasonakai** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。

**Comment by jyasco** [comment]
ご確認いただきありがとうございます！
引き続きどうぞよろしくお願いいたします。
