### ISSUE TITLE
"Issueベースの開発"レビュー依頼

### ISSUE THREAD

**Issue by jyasco** [jyasco/purin-mania#67]
## Webアプリの概要
「Purin Mania」は、プリン愛好家のためのレビュー・検索アプリです。
ユーザーはプリンの固さや甘さなどを詳細に評価し、共有できます。
理想のプリンを自分の好みから検索したり、地図上で簡単に見つけることができます。

## 1週間辺りの開発に向けられる時間
- 1週間あたり：25時間
- 1週間あたりのストーリポイント消化目安：12

## ProjectsのURL
[PurinMania開発プロジェクト](https://github.com/users/jyasco/projects/1/views/1)

## MVPリリースまで
- [ ] rails new
- [ ] デプロイ
- [ ] トップページ
- [ ] ヘッダー/フッター
- [ ] rubocop導入
- [ ] 日本語化
- [ ] アカウント登録
- [ ] ログイン/ログアウト機能
- [ ] 投稿作成機能
- [ ] 投稿一覧機能
- [ ] 投稿編集機能
- [ ] 投稿削除機能
- [ ] 一覧ページでの検索機能
- [ ] キーワード検索機能
- [ ] 甘さ/固さの絞り込み検索機能
- [ ] マイページ
- [ ] マイページ編集
- [ ] マイページに自分の投稿一覧の表示
- [ ] お問い合わせフォーム
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] Xシェア機能
- [ ] 静的ogp

## MVP後
- [ ] パスワードリセット機能
- [ ] GoogleMapAPIを利用した地図の表示
- [ ] 地図ページでの検索機能
- [ ] 投稿詳細に地図を表示
- [ ] 現在地取得
- [ ] Google認証
- [ ] ブックマーク機能
- [ ] 動的OGP
- [ ] カテゴリー選択の実装
    - 投稿時にカフェ・菓子店/市販で選択できる機能
    - 投稿作成画面で、カフェ・菓子店を選択したもののみ住所項目を表示
    - 住所のあるもののみ地図上に表示
- [ ] ページタイトル
- [ ] 検索クリア機能
- [ ] CI（GitHubActions）
- [ ] 独自ドメイン
- [ ] レスポンシブ対応

## MVPレビュー依頼予定日
予定日：2024年 12月 8日

**Comment by kenchasonakai** [comment]
LGTMです！
